### ISSUE TITLE
please add following programs to exclusion

### ISSUE THREAD

**Issue by dragonGRaf** [rcmaehl/FreezeToStock#16]
default install directory is 
C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

**Comment by dragonGRaf** [comment]
nicetaskbar and eartrumpet from microsoft store

(if there is that question) yes i found that you can put custom stuff but would be nice to be added for people that use the same programs and dont need to add them themselfs

**Comment by dragonGRaf** [comment]
what kind of file do i need to load?
![image](https://user-images.githubusercontent.com/65346683/204115220-21d18c52-f943-4f31-8761-41aaf28939d8.png)

**Comment by rcmaehl** [comment]
@drachedachte1 

Put the following into notepad and save as `CustomExclusion.def`

```
Process,EarTrumpet.exe
Process,Brave.exe
Process,NiceTaskbar.exe
```

**Comment by dragonGRaf** [comment]
thx will do
