### ISSUE TITLE
Freeze LOGITECH WIRELESS COMBO MK330

### ISSUE THREAD

**Issue by latitude23** [rcmaehl/FreezeToStock#2]
It is freezing my wireless keyboard and Mouse (usb dongle). I couldn't find any Process/Service to Exclude.

**Comment by rcmaehl** [comment]
Hi @latitude23,

Can you choose File -> Export and attach that file to this ticket?

**Comment by latitude23** [comment]
Here the attachment. (Your app export with csv file format, GitHub doesn't support that extension so I change your csv file in pdf)
[export.pdf](https://github.com/rcmaehl/FreezeToStock/files/5317115/export.pdf)
If you need it in another format, just tell. Thank you.

ABOUT behavior of my wireless K and M, this is what is really happening.
- when i freeze, as long as i stay in your app's window it works. If i click outside (on the desktop or launching app from tray) then it starts to lag heavily. If i come back to your app's windows and click for example File - Export, then it stops to lag and come back to normal. I click outside then it lags again. Same inside what ever for app, games, explorer,... included.
- Same for the keyboard.

**Comment by micwoj92** [comment]
I'm pretty sure it would be much better to just change .csv to .txt

**Comment by latitude23** [comment]
Yes, you are right, than you.
Here is the file:
[export.txt](https://github.com/rcmaehl/FreezeToStock/files/5317140/export.txt)

**Comment by rcmaehl** [comment]
Hi

Please try the following Custom Definition and let me know if it fixes it.
To add it, rename the file from .txt to .def, then choose Exclusions -> Custom -> Add Custom.
If it does I'll add it to FreezeToStock 1.2

[LogiTest.txt](https://github.com/rcmaehl/FreezeToStock/files/5318359/LogiTest.txt)

**Comment by latitude23** [comment]
Hi,
first i renamed your file in .def
After i add it with "Add Custom"
It doesn't change anything.
I did it several times
So I exported the file, renamed in .txt, and read it.
I cannot find anywhere the exclusions you sent to me: "KHALMNPR.exe" and "SetPoint.exelogi"
Maybe is there a problem with the Exclusion process...
Also, wireless M and K are common, always USB dongle. Maybe you can borrow it from someone and try to reproduce.
I stay anyway here if I can help.
[export02.txt](https://github.com/rcmaehl/FreezeToStock/files/5319043/export02.txt)

**Comment by rcmaehl** [comment]
Make sure you're running Task Manager as administrator.

I've fix a minor typo I made in the original file, try now.
[LogiTest.txt](https://github.com/rcmaehl/FreezeToStock/files/5320871/LogiTest.txt)

**Comment by latitude23** [comment]
Hi Friend,
last time I downloaded your V1.2 it didn't work, I had the same freezing problem.
I gave up for a while.
Today I tried your new version and it is working exactly fine. I don't have problem anymore. Nice!
To play games I use to run before "Wise Game Booster".  After running your FTS, I tried this app. It gave me more 4 Services that can be stopped.
Any way thanks for the useful
![after freezing](https://user-images.githubusercontent.com/72195024/97084193-f68f2f00-1647-11eb-8e7a-70d8a961efa2.PNG)
 app.

**Comment by rcmaehl** [comment]
> Hi Friend,
> last time I downloaded your V1.2 it didn't work, I had the same freezing problem.
> I gave up for a while.
> Today I tried your new version and it is working exactly fine. I don't have problem anymore. Nice!
> To play games I use to run before "Wise Game Booster". After running your FTS, I tried this app. It gave me more 4 Services that can be stopped.
> Any way thanks for the useful
> ![after freezing](https://user-images.githubusercontent.com/72195024/97084193-f68f2f00-1647-11eb-8e7a-70d8a961efa2.PNG)
> app.

Will look into those and add if safe. Thank you!
