### ISSUE TITLE
Just one question I had.

### ISSUE THREAD

**Issue by OneSlize** [rcmaehl/FreezeToStock#6]
Hello mate, love this little program. Really helps on my older hardware. High Five Brutha! 

Just one question though, how do I add custom exclusions? It asks for a configurating file , I thought it would be able to choose certain executables and add it to the custom exclusion. Thank you

**Comment by micwoj92** [comment]
In releases there is ExampleCustomExclusion.def file which, well, is an example. It's just a text file so you can edit it with notepad and when you save it make sure that it is .def and not .def.txt or something like that. You just need to know the executable name to put it there.

**Comment by OneSlize** [comment]
> In releases there is ExampleCustomExclusion.def file which, well, is an example. It's just a text file so you can edit it with notepad and when you save it make sure that it is .def and not .def.txt or something like that. You just need to know the executable name to put it there.

Thanks so much.
