### ISSUE TITLE
Checking for updates while system is frozen causes app to stop responding

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/FreezeToStock#7]
How to reproduce:
1. Freeze system
2. Check for updates

This causes the application to stop responding, after opening FTS again, freezing and then unfreezing, the problem persists.
This also makes NotCpuCores updates cause stop responding. Only way to resolve seems to be to restart the system.

**Comment by rcmaehl** [comment]
Fixed in 1066a0e, further improved in b2aa70a

**Comment by micwoj92** [comment]
Thank you!
