### ISSUE TITLE
Icon misses from main menu in CI build

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/FreezeToStock#9]
The snowflake icon present in screenshot in readme misses in CI build. This is due to not using AutoIt3Wrapper.

Information I have so far:

1. AutoIt3Wrapper does not seem to work when launching it from command line with arguments.
for example `/in FTS.au3` should work but it does not.

2. AutoIt3Wrapper does work when launching it from command line without arguments and then selecting FTS.au3 from the file picker.
`./AutoIt3.exe "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3"`
The above line will launch file picker, after picking FTS.au3 there it compiles with all options set using  `#AutoIt3Wrapper` properly.

I think this is autoit issue but I'm putting it here so I don't forget to look more into it.

**Comment by rcmaehl** [comment]
Resolved in #10
